# Generated by Django 4.2 on 2023-04-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('cargo', models.CharField(max_length=40)),
                ('area', models.CharField(max_length=40)),
                ('sueldo', models.DecimalField(decimal_places=4, max_digits=11)),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
    ]
